Factory/Models/Assignment.cs
namespace Factory.Models
{
  public class Assignment
    {       
        public int AssignmentId { get; set; }
        public int MachineId { get; set; }
        public int EngineerId { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual Engineer Engineer { get; set; }
    }
}

Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<Assignment>();
    }

    public int EngineerId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Assignment> JoinEntities { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<Assignment> Assignment { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models

{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<Assignment>();
    }
    public int MachineId { get; set; }
    public string Description { get; set; }
    
    public virtual ICollection<Assignment> JoinEntities { get;}
  }
}

Factory/Controllers/EngineersController.cs
// using Microsoft.EntityFrameworkCore;
// using Microsoft.AspNetCore.Mvc;
// using Factory.Models;
// using System.Collections.Generic;
// using System.Linq;

// namespace Factory.Controllers
// {
//   public class EngineersController : Controller
//   {
//     private readonly FactoryContext _db;

//     public EngineersController(FactoryContext db)
//     {
//       _db = db;
//     }

//     public ActionResult Index()
//     {
//       List<Engineer> model = _db.Engineers.ToList();
//       return View(model);
//     }

//     public ActionResult Create()
//     {
//       return View();
//     }

//     [HttpPost]
//     public ActionResult Create(Engineer engineer)
//     {
//       _db.Engineers.Add(engineer);
//       _db.SaveChanges();
//       return RedirectToAction("Index");
//     }

//     public ActionResult Details(int id)
//     {
//       Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
//       return View(thisEngineer);
//     }
//     public ActionResult Edit(int id)
//     {
//       var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
//       return View(thisEngineer);
//     }

//     [HttpPost]
//     public ActionResult Edit(Engineer engineer)
//     {
//       _db.Entry(engineer).State = EntityState.Modified;
//       _db.SaveChanges();
//       return RedirectToAction("Index");
//     }

//     public ActionResult Delete(int id)
//     {
//       var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
//       return View(thisEngineer);
//     }

//     [HttpPost, ActionName("Delete")]
//     public ActionResult DeleteConfirmed(int id)
//     {
//       var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
//       _db.Engineers.Remove(thisEngineer);
//       _db.SaveChanges();
//       return RedirectToAction("Index");
//     }
//   }
// }

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if (EngineerId != 0)
    {
      _db.Assignment.Add(new Assignment() { EngineerId = EngineerId, MachineId = machine.MachineId });
      _db.SaveChanges();
    }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/Create.cshtml
@* @{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a new engineer</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new engineer" />
}
<p>@Html.ActionLink("Show all engineers", "Index")</p> *@

Factory/Views/Engineers/Delete.cshtml
@* @{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this engineer?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index") *@

Factory/Views/Engineers/Details.cshtml
@* @{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p> *@

Factory/Views/Engineers/Edit.cshtml
@* @{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit</h2>

<h4>Edit this engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p> *@

Factory/Views/Engineers/Index.cshtml
@* @{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>Engineers</h1>

@if (@Model.Count == 0)
{
  <h3>No engineers have been added yet!</h3>
} 

<ul>
  @foreach(Engineer engineer in Model)
  {
    <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new engineer", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p> *@

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>List of Factory's Engineers and Machines</h1>
<p>@Html.ActionLink("See all machines", "Index", "Machines")</p> <p>@Html.ActionLink("See all engineers", "Index", "Engineers")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new machine</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)

  @Html.Label("Select engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Add new machine" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all machines", "Index")</p>

Factory/Views/Machines/Delete.cshtml
@* @{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this machine?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index") *@

Factory/Views/Machines/DeleteAll.cshtml
@* @{
  Layout = "_Layout";
}

<h1>Your list has been cleared!</h1>
<p><a href="/clients">Back to list.</a></p> *@

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)<h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This machine does not belong to any engineers</p>
}
else
{
  <h4>Engineers the machine belongs to:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Engineer.Name</li>
  }
  </ul>
}

<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Edit.cshtml
@* @{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.LabelFor(model => model.Engineer)
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p> *@

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Machines</h1>

@if (@Model.Count == 0)
{
  <h3>No machines have been added yet!</h3>
} 

@foreach (Machine machine in Model)
{
  <li>@Html.ActionLink($"{machine.Description}", "Details", new { id = machine.MachineId }) </li>
}

<p>@Html.ActionLink("Add new machine", "Create")</p>

Factory/Views/Shared/Footer.cshtml
<div id="footer">Dr. Sillystringz's Factory</div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>List of Factory's Engineers and Machines</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @await Html.PartialAsync("Footer")
  </body>
</html>